[project]
name = '009Market'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.nftmarketplace]
path = 'contracts/nftmarketplace.clar'
clarity_version = 2
epoch = '3.0'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
